---
title: "Getting and Cleaning Data_ run_analysis"
author: "Joanna Tyszkiewicz Georgescu"
date: "February 22, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r, echo=FALSE,results='hide',message=FALSE, warning=FALSE}
library(plyr)
library(dplyr)
library(tidyverse)
library(data.table)
```

##Load Data
```{r}
setwd("C:\\Users\\Joanna\\Desktop\\R_coursera\\GettingAndCleaningData\\")

path <- getwd()
url <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
download.file(url, file.path(path, "dataFiles.zip"))
unzip(zipfile = "dataFiles.zip", list=FALSE)
```

##Load activity labels and features
```{r}
activityLabels <- read.table(file.path(path, "UCI HAR Dataset/activity_labels.txt"), col.names = c("classLabels", "activityName"))
activityLabels
features <- read.table(file.path(path, "UCI HAR Dataset/features.txt"), col.names = c("index", "featureNames"))
f <- grep("(mean|std)\\(\\)", features[, "featureNames"])
measurements <- features[f, "featureNames"]
measurements <- gsub('[()]', '', measurements)
```

##Load Train datasets
```{r}
XTrain <- read.table(file.path(path, "UCI HAR Dataset/train/X_train.txt"))[, f]
setnames(XTrain,old=(colnames(XTrain)), new=measurements)

YTrain <- read.table(file.path(path, "UCI HAR Dataset/train/Y_train.txt") , col.names = c("SubjectNum"))
trainSubjects <- read.table(file.path(path, "UCI HAR Dataset/train/subject_train.txt")
                     ,col.names = c("SubjectNum"))
Train <- cbind(trainSubjects, YTrain, XTrain)
```

##Load Test datasets
```{r}
XTest <- read.table(file.path(path, "UCI HAR Dataset/test/X_test.txt"))[, f]
setnames(XTest,old=(colnames(XTest)), new=measurements)
YTest <- read.table(file.path(path, "UCI HAR Dataset/test/Y_test.txt")
                        ,col.names = c("Activity"))
testSubjects <- read.table(file.path(path, "UCI HAR Dataset/test/subject_test.txt")
                      ,col.names = c("SubjectNum"))
Test <- cbind(testSubjects, YTest, XTest)

colnames (Train)[2] <- "Activity"
colnames(Test)
colnames(Train)
```

##Merge datasets, combine with labels, create second tidy set with the average of each variable for each activity and each subject.
```{r}
combined <- rbind(Train, Test, fill=TRUE)

combined[["Activity"]] <- factor(combined[, "Activity"]
                                 , levels = activityLabels[["classLabels"]]
                                 , labels = activityLabels[["activityName"]])

combined[["SubjectNum"]] <- as.factor(combined[, "SubjectNum"])
combined <- reshape2::melt(data = combined, id = c("SubjectNum", "Activity"))
combined <- reshape2::dcast(data = combined, SubjectNum + Activity ~ variable, fun.aggregate = mean)
data.table::fwrite(x = combined, file = "sTidyData.txt", row.name = FALSE)
```